# Slinky Operator — place pods on management nodes
operator:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: doks.digitalocean.com/node-pool
                operator: In
                values: [mgmt]
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

webhook:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: doks.digitalocean.com/node-pool
                operator: In
                values: [mgmt]
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
